# This is a basic workflow to help you get started with Actions

name: regression_train_pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install dvc[s3]
          
          pip install -r requirements.txt
           
          dvc repro 
          
          git fetch --prune --unshallow
          echo "## Parameters Changes  " >> report.md
          dvc params diff --show-md develop  >> report.md
          echo "## Evaluation Metrics  " >> report.md
          dvc metrics diff --show-md develop >> report.md
        
          cml-send-comment report.md 